#!/bin/bash

while true
do
    echo "Running script at $(date)"
    
    bash <(curl -s https://raw.githubusercontent.com/fahmibinamin/24-7/refs/heads/main/neverOFF)
    
    echo "Sleeping for 1 hour..."
    sleep 3600
done
